version: '4'

services:
  acc_frontend:
    ports:
      - ":3000"
    build: frontend/
    networks:
      - main_network
    depends_on:
      - acc_backend

  acc_backend:
    ports:
      - ":3001"
    build: 
      context: backend/
    env_file:
      - "./backend/.env"
    networks:
      - main_network

networks:
  main_network:
        name: main_network 
        external: true